/**
 *
 * @return [18,19,29...49,50]
 * @type {number[]}
 */
const ages = Array(50 - 17).fill(0).map((e, i) => i + 18);

const nationalities = [
  'African',
  'American',
  'Argentine',
  'Asian-Other',
  'Australian',
  'AU-European',
  'Bruneian',
  'Brazilian',
  'British',
  'Canadian',
  'Chinese',
  'Colombian',
  'Cook Islands',
  'Dutch',
  'English',
  'Filipino',
  'Fijian',
  'French',
  'German',
  'Greek',
  'Hawaiian',
  'Indian',
  'Indonesian',
  'Italian',
  'Jamaican',
  'Japanese',
  'Korean',
  'Latino',
  'Malaysian',
  'Middle Easter',
  'Mongolian',
  'NZ-European',
  'NZ-Part Maori',
  'Polynesian',
  'Russian',
  'Romania',
  'Samoan',
  'Singapore',
  'Spanish',
  'Sri Lankan',
  'Swedish',
  'Tahitian',
  'Taiwanese',
  'Thai',
  'Ukrainian',
  'Vietnamese',
  'Other',
];

/**
 *
 * @return [150cm,152cm,154cm...198cm,200cm]
 * @type {string[]}
 */
const heights = Array(Math.ceil((200 - 149) / 2)).fill(0).map((e, i) => 2 * i + 150 + 'cm');

/**
 * @return [40kg,41kg,42kg...89kg,90kg]
 * @type {string[]}
 */
const weights = Array(90 - 39).fill(0).map((e, i) => i + 40 + 'kg');
const busts = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];

/**
 * @return [5,6,7..,24,25]
 * @type {number[]}
 */
const bodySizes = Array(25 - 4).fill(0).map((e, i) => i + 5);

const personalTypes = [
  'Natural',
  'Shaven',
  'Trimmed',
];

const serviceTypes = [
  'Full Service',
  'Full Service & BDSM',
];
const workingStatues = [
  'Private',
  'Agency',
];
const parkingTypes = [
  'Paid Parking',
  'Paid Parking & Street Parking',
  'Private Parking',
  'Private Parking & Street Parking',
  'Street Parking',
];
const orientations = [
  'Lesbian',
  'Transsexual',
  'Bisexual',
];
const timeOptions = [
  "9am",
  "10am",
  "11am",
  "12pm",
  "1pm",
  "2pm",
  "3pm",
  "4pm",
  "5pm",
  "6pm",
  "7pm",
  "8pm",
  "9pm",
  "10pm",
  "11pm",
  "12am",
  "1am",
  "2am",
  "3am",
  "4am",
  "5am",
  "6am",
  "7am",
  "8am",
  "Midnight",
  "Late",
  "OFF",
  "Please ask",
];
const countries = ['New Zealand'];

const nzCities = [
  'Auckland',
  'Northland',
  'Hamilton',
  'Central North Island',
  'Tauranga',
  'Wellington',
  'Christchurch',
  'South Island',
];

const aucklandSuburbs = [
  'Airport Oaks',
  'Albany',
  'Alfriston',
  'Ararimu',
  'Arch Hill',
  'Ardmore',
  'Avondale',
  'Balmoral',
  'Bayswater',
  'Bayview',
  'Beach Haven',
  'Beachlands',
  'Belmont',
  'Birkdale',
  'Birkenhead',
  'Blockhouse Bay',
  'Bombay',
  'Botany Downs',
  'Brookby',
  'Browns Bay',
  'Buckland',
  'Bucklands Beach',
  'Burswood',
  'Campbells Bay',
  'Castor Bay',
  'CBD',
  'Chapel Downs',
  'Chatswood',
  'Cheltenham',
  'Clarks Beach',
  'Clendon Park',
  'Clevedon',
  'Clover Park',
  'Cockle Bay',
  'Conifer Grove',
  'Crown Hill',
  'Cuthill',
  'Dairy Flat',
  'Dannemora',
  'Devonport',
  'East Tamaki',
  'Eastern Beach',
  'Eden Terrace',
  'Eden Valley',
  'Ellerslie',
  'Epsom',
  'Fairview Heights',
  'Farm Cove',
  'Favona',
  'Flamboro Heights',
  'Flat Bush',
  'Forrest Hill',
  'Freemans Bay',
  'Glen Eden',
  'Glen Innes',
  'Glendene',
  'Glendowie',
  'Glenfield',
  'Glenvar',
  'Golflands',
  'Goodwood Heights',
  'Grafton',
  'Green Bay',
  'Greenhithe',
  'Greenlane',
  'Greenmeadows',
  'Greenwoods Corner',
  'Grey Lynn',
  'Gulf Harbour',
  'Half Moon Bay',
  'Hauraki',
  'Helensville',
  'Henderson',
  'Herald Island',
  'Herne Bay',
  'Heron Point',
  'Highbury',
  'Highland Park',
  'Hill Park',
  'Hillcrest',
  'Hillsborough',
  'Hobsonville',
  'Howick',
  'Huia',
  'Hunua',
  'Karaka',
  'Karekare',
  'Kelston',
  'Kingseat',
  'Kingsland',
  'Kohimarama',
  'Konini',
  'Laingholm',
  'Leigh',
  'Lincoln',
  'Long Bay',
  'Longford Park',
  'Lynfield',
  'Mahia Park',
  'Mairangi Bay',
  'Mangere',
  'Mangere Bridge',
  'Mangere East',
  'Manly',
  'Manukau',
  'Manukau Heights',
  'Manurewa',
  'Manurewa East',
  'Maraetai',
  'Marlborough',
  'Massey',
  'Matakana',
  'McLaren Park',
  'Meadowbank',
  'Meadowlands',
  'Meadowood',
  'Mellons Bay',
  'Middlemore',
  'Milford',
  'Millwater',
  'Mission Bay',
  'Morningside',
  'Mount Albert',
  'Mount Eden',
  'Mount Roskill',
  'Mount Wellington',
  'Muriwai',
  'Murphys Heights',
  'Murrays Bay',
  'Narrow Neck',
  'New Lynn',
  'New Windsor',
  'Newmarket',
  'Newton',
  'North Harbour',
  'North Park',
  'Northcote',
  'Northcote Central',
  'Northcote Point',
  'Northcross',
  'Okura',
  'One Tree Hill',
  'Onehunga',
  'Opaheke',
  'Orakei',
  'Oranga',
  'Oratia',
  'Orere Point',
  'Orewa',
  'Otahuhu',
  'Otara',
  'Oteha',
  'Owairaka',
  'Paerata',
  'Pahurehure',
  'Pakuranga',
  'Panmure',
  'Papakura',
  'Paparimu',
  'Papatoetoe',
  'Paremoremo',
  'Parnell',
  'Patumahoe',
  'Penrose',
  'Pinehill',
  'Point Chevalier',
  'Point England',
  'Ponsonby',
  'Porchester Park',
  'Puhinui',
  'Puhoi',
  'Pukekohe',
  'Randwick Park',
  'Ranui',
  'Red Beach',
  'Red Hill',
  'Redoubt Park',
  'Remuera',
  'Richmond Park',
  'Riverhead',
  'Rosedale',
  'Rosehill',
  'Rothesay Bay',
  'Royal Heights',
  'Royal Oak',
  'Saint Heliers',
  'Saint Johns',
  'Saint Marys Bay',
  'Sandringham',
  'Sandspit',
  'Schnapper Rock',
  'Settlers Cove',
  'Shelly Park',
  'Silkwood Heights',
  'Silverdale',
  'Somerville',
  'Stanley Bay',
  'Stanley Point',
  'Stanmore Bay',
  'Stonefields',
  'Sunnyhills',
  'Sunnynook',
  'Sunnyvale',
  'Swanson',
  'Takanini',
  'Takapuna',
  'Tamaki',
  'Te Atatu',
  'Te Atatu Peninsula',
  'Te Atatu South',
  'Te Hana',
  'Te Papapa',
  'The Gardens',
  'Three Kings',
  'Titirangi',
  'Torbay',
  'Totara Heights',
  'Totara Vale',
  'Tuscany Estate',
  'Unsworth Heights',
  'Waiake',
  'Waiau Pa',
  'Waikowhai',
  'Waimahia Landing',
  'Waimauku',
  'Wairau Valley',
  'Waiuku',
  'Waiwera',
  'Warkworth',
  'Waterview',
  'Wattle Cove',
  'Wattle Downs',
  'Wellsford',
  'West Harbour',
  'Western Heights',
  'Western Springs',
  'Westfield',
  'Westgate',
  'Westlake',
  'Westmere',
  'Weymouth',
  'Whangaparaoa',
  'Whenuapai',
  'Whitford',
  'Windsor Park',
  'Wiri',
];
const northlandSuburbs = [
  'Dargaville',
  'Hikurangi',
  'Kaikohe',
  'Kaitaia',
  'Kawakawa',
  'Kerikeri',
  'Mangawhai',
  'Moerewa',
  'Paihia',
  'Ruakaka',
  'Taipa-Mangonui',
  'Waipu',
  'Whangarei',
];
const hamiltonSuburbs = [
  'Ashmore',
  'Beerescourt',
  'Callum Brae',
  'CBD',
  'Chartwell',
  'Chedworth Park',
  'Claudelands',
  'Crawshaw',
  'Deanwell',
  'Dinsdale',
  'Enderley',
  'Fairfield',
  'Fairview Downs',
  'Fitzroy',
  'Flagstaff',
  'Forest Lake',
  'Frankton',
  'Glenview',
  'Grandview Heights',
  'Hamilton East',
  'Hamilton North',
  'Hamilton West',
  'Harrowfield',
  'Huntington',
  'Livingstone',
  'Maeroa',
  'Magellan Rise',
  'Melville',
  'Nawton',
  'Naylor',
  'Peacocke',
  'Pukete',
  'Queenwood',
  'Riverlea',
  'Rotokauri',
  'Rototuna',
  'Ruakura',
  'Somerset Heights',
  'St Andrews',
  'St James Park',
  'St Petersburg',
  'Stonebridge',
  'Te Kowhai',
  'Te Rapa',
  'Temple View',
  'Thornton',
  'Whitiora',
];
const centralNorthIslandSuburbs = [
  'Feilding',
  'Gisborne',
  'Hastings',
  'Hawkes Bay',
  'Levin',
  'Masterton',
  'Napier',
  'New Plymouth',
  'Palmerston North',
  'Rotorua',
  'Taupo',
  'Te Kauwhata',
  'Waikato',
  'Wanganui',
  'Whakatane',
];
const taurangaSuburbs = [
  'Bellevue',
  'Bethlehem',
  'Brookfield',
  'Gate Pa',
  'Greerton',
  'Hairini',
  'Judea',
  'Matua',
  'Maungatapu',
  'Ohauiti',
  'Otumoetai',
  'Parkvale',
  'Poike',
  'Pyes Pa',
  'Tauranga',
  'Tauranga South',
  'Tauriko',
  'Welcome Bay',
];
const wellingtonSuburbs = [
  'Alicetown',
  'Aotea',
  'Arakura',
  'Aro Valley',
  'Ascot Park',
  'Ava',
  'Avalon',
  'Berhampore',
  'Birchville',
  'Borough of Onslow',
  'Boulcott',
  'Breaker Bay',
  'Brooklyn',
  'Brown Owl',
  'Camborne',
  'Cannons Creek',
  'CBD',
  'Churton Park',
  'Clouston Park',
  'Crofton Downs',
  'Days Bay',
  'Eastbourne',
  'Ebdentown',
  'Elderslea',
  'Emerald Hill',
  'Epuni',
  'Glendale',
  'Glenside',
  'Gracefield',
  'Grenada',
  'Grenada North',
  'Happy Valley',
  'Harbour View',
  'Hataitai',
  'Haywards',
  'Heretaunga',
  'Homedale',
  'Hongoeka',
  'Horokiwi',
  'Houghton Bay',
  'Island Bay',
  'Johnsonville',
  'Judgeford',
  'Kaiwharawhara',
  'Karaka Bays',
  'Karehana Bay',
  'Karori',
  'Kelburn',
  'Kelson',
  'Kenepuru',
  'Khandallah',
  'Kilbirnie',
  'Kingsley Heights',
  'Kingston',
  'Korokoro',
  'Linden',
  'Lyall Bay',
  'Makara',
  'Mana',
  'Mangaroa',
  'Manor Park',
  'Maoribank',
  'Maungaraki',
  'Maupuia',
  'Maymorn',
  'Melling',
  'Melrose',
  'Miramar',
  'Moera',
  'Moonshine',
  'Moonshine Valley',
  'Mornington',
  'Mount Cook',
  'Mount Victoria',
  'Naenae',
  'Newlands',
  'Newtown',
  'Ngaio',
  'Ngauranga',
  'Normandale',
  'Northland',
  'Ohariu',
  'Onepoto',
  'Oriental Bay',
  'Owhiro Bay',
  'Papakowhai',
  'Paparangi',
  'Paremata',
  'Parkdale',
  'Parkway',
  'Pauatahanui',
  'Petone',
  'Pinehaven',
  'Plimmerton',
  'Pomare',
  'Pukerua Bay',
  'Riverstone Terraces',
  'Rongotai',
  'Roseneath',
  'Seatoun',
  'Seaview',
  'Shelly Bay',
  'Silverstream',
  'Stokes Valley',
  'Strathmore Park',
  'Taitā',
  'Takapu Valley',
  'Takapuwahia',
  'Tawa',
  'Te Aro',
  'Te Marua',
  'Thorndon',
  'Timberlea',
  'Tirohanga',
  'Titahi Bay',
  'Totara Park',
  'Trentham',
  'Upper Hutt central business district',
  'Vogeltown',
  'Wadestown',
  'Wainuiomata',
  'Waitangirua',
  'Waiwhetū',
  'Wallaceville',
  'Waterloo',
  'Whitby',
  'Whitemans Valley',
  'Wilton',
  'Wingate',
  'Woburn',
  'Woodridge',
  'Worser Bay',
];
const christchurchSuburbs = [
  'Addington',
  'Aidanfield',
  'Aranui',
  'Avonhead',
  'Avonside',
  'Barrington',
  'Beckenham',
  'Belfast',
  'Bexley',
  'Bishopdale',
  'Bottle Lake',
  'Bromley',
  'Brooklands',
  'Bryndwr',
  'Burnside',
  'Burwood',
  'Cashmere',
  'CBD',
  'Clifton',
  'Cracroft',
  'Dallington',
  'Diamond Harbour',
  'Duvauchelle',
  'Edgeware',
  'FendaltonFerrymead',
  'Halswell',
  'Harewood',
  'Heathcote Valley',
  'Hei Hei',
  'Hoon Hay',
  'Hornby',
  'Huntsbury',
  'Ilam',
  'Kennedys Bush',
  'Linwood',
  'Mairehau',
  'Merivale',
  'Moncks Bay',
  'Mount Pleasant',
  'Murray Aynsley Hill',
  'New Brighton',
  'Opawa',
  'Papanui',
  'Parklands',
  'Phillipstown',
  'Redcliffs',
  'Redwood',
  'Riccarton',
  'Richmond',
  'Richmond Hill',
  'Scarborough',
  'Shirley',
  'Sockburn',
  'Somerfield',
  'Southshore',
  'Spencerville',
  'Spreydon',
  'St Albans',
  'St Andrews Hill',
  'St Martins',
  'Strowan',
  'Sumner',
  'Sydenham',
  'Upper Riccarton',
  'Waimairi Beach',
  'Wainoni',
  'Waltham',
  'Westmorland',
  'Wigram',
  'Woolston',
];
const southIslandSuburbs = [
  'Alexandra',
  'Ashburton',
  'Blenheim',
  'Dunedin',
  'Greymouth',
  'Invercargill',
  'Nelson',
  'Oamaru',
  'Queenstown',
  'South Canterbury',
  'Timaru',
  'Wanaka',
];

const extraServiceTypes = [
  'Anal sex',
  'BD - bondage+discipline',
  'Bachelor party',
  'Balls licking+sucking',
  'Bi double',
  'Body slide',
  'Bondage',
  'Breast play',
  'Brown shower',
  'CBT - cock and ball torture',
  'COB - cum on body',
  'COF - cum on face',
  'Costumes and role play',
  'Couples',
  'Cuddling',
  'Deep throat',
  'Dinner dates',
  'Dirty talk',
  'Disabled clients',
  'Double penetration',
  'Erotic sensual massage',
  'Fetishes',
  'Filming',
  'Fire and ice - hot and cold BJ',
  'Foot fetish',
  'French kissing',
  'GFE',
  'Gives canings',
  'Gives golden shower',
  'Gives oral',
  'Hand relief',
  'Lactating',
  'Light kissing',
  'Light spanking',
  'Multi shots',
  'Mutual masturbation',
  'Mutual oral',
  'Oil body slide',
  'Oil massage',
  'PSE - porn star experience',
  'Prostate massage',
  'Receives canings',
  'Receives golden showers',
  'Receives oral',
  'Sexy lingerie and stocking',
  'Shower together',
  'Squirting',
  'Straight double',
  'Strap on',
  'Strip tease',
  'Touching',
  'Toys on me',
  'Toys on you',
  'Variety of positions',
  'Please Ask',
];

const contactPreferenceTypes = [
  'Text Only',
  'No Blocked Numbers',
  'Text Preferred',
  'Call For Booking',
];

export {
  ages,
  nationalities,
  heights,
  weights,
  busts,
  bodySizes,
  personalTypes,
  serviceTypes,
  workingStatues,
  parkingTypes,
  orientations,
  timeOptions,
  countries,
  nzCities,
  extraServiceTypes,
  contactPreferenceTypes,
  aucklandSuburbs,
  northlandSuburbs,
  hamiltonSuburbs,
  centralNorthIslandSuburbs,
  taurangaSuburbs,
  wellingtonSuburbs,
  christchurchSuburbs,
  southIslandSuburbs,
}
